# Generated by Django 5.2.14 on 2026-05-24 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='ies.estado')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('nome', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='IES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(blank=True, max_length=30)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('uf', models.CharField(max_length=2)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, max_length=300)),
                ('status_juridico', models.CharField(blank=True, choices=[('Federal', 'Federal'), ('Estadual', 'Estadual'), ('Municipal', 'Municipal'), ('Privada', 'Privada')], max_length=20)),
                ('areas_pesquisa', models.TextField(blank=True)),
                ('area_conhecimento', models.CharField(blank=True, max_length=200)),
                ('especializacao', models.BooleanField(default=False)),
                ('nota_especializacao', models.IntegerField(blank=True, null=True)),
                ('mestrado', models.BooleanField(default=False)),
                ('doutorado', models.BooleanField(default=False)),
                ('nota_pos_capes', models.IntegerField(blank=True, null=True)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ies_list', to='ies.cidade')),
            ],
            options={
                'verbose_name': 'IES',
                'verbose_name_plural': 'IES',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CursoPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_base', models.IntegerField(blank=True, null=True)),
                ('grande_area', models.CharField(blank=True, max_length=100)),
                ('area_conhecimento', models.CharField(blank=True, max_length=200)),
                ('subarea', models.CharField(blank=True, max_length=200)),
                ('especialidade', models.CharField(blank=True, max_length=200)),
                ('area_avaliacao', models.CharField(blank=True, max_length=200)),
                ('nome_programa', models.CharField(blank=True, max_length=300)),
                ('nome_curso', models.CharField(blank=True, max_length=300)),
                ('grau', models.CharField(blank=True, choices=[('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado'), ('MESTRADO PROFISSIONAL', 'Mestrado Profissional')], max_length=30)),
                ('conceito', models.IntegerField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, max_length=50)),
                ('ies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_pos', to='ies.ies')),
            ],
            options={
                'ordering': ['ies__nome', 'nome_curso'],
            },
        ),
    ]
